spring:
  datasource:
    url: jdbc:h2:mem:valaas-test;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: false
  data:
    redis:
      host: localhost
      port: 6379

valaas:
  cache:
    enabled: false
  messaging:
    enabled: false
  security:
    username: test-user
    password: test-pass

nats:
  url: nats://localhost:4222

logging:
  level:
    org.hibernate.SQL: debug
